version: "3"
services:
  web:
    image: tms-api
    volumes: 
      - "/tmp:/tmp"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
    ports:
      - "8090:80"
    networks:
      - webnet
networks:
  webnet: 